services:
  # 1. The Database (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: hrms_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: HRMS
    volumes:
      - postgres_data:/var/lib/postgresql/data

# This was missing:
volumes:
  postgres_data: